module.exports = {
  images: {
    domains: [
      "images.unsplash.com",
      "dummyimage.com",
      "i.dummyjson.com",
      "ucoz.com",
      "tinypic.com",
      "mashable.com",
      "123-reg.co.uk",
      "wikipedia.org",
      "studiopress.com",
      "businessinsider.com",
      "miitbeian.gov.cn",
      "drupal.org",
      "toplist.cz",
      "ed.gov",
      "in.wikipedia.org",
      "biglobe.ne.jp",
      "pagesperso-orange.fr",
      "illinois.edu",
      "uiuc.edu",
      "storify.com",
      "reference.com",
      "soup.io",
      "java.com",
      "angelfire.com",
      "goodreads.com",
      "prnewswire.com",
      "economist.com",
      "blogs.com",
      "vkontakte.ru",
      "google.co.uk",
      "shop-pro.jp",
      "state.gov",
      "readymadeui.com/readymadeui.svg",
      "readymadeui.com",
      "pagedone.io",
    ],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.unsplash.com",
        port: "",
        pathname: "/**",
      },
    ],
  },
};
