enum ProductCategory {
  Electronics = "Electronics",
  Clothing = "Clothing",
  Books = "Books",
  HomeDecor = "Home Decor",
  Sports = "Sports",
  Health = "Health",
  Toiletries = "Toiletries",
  Pets = "Pets",
  Beauty = "Beauty",
  Fashion = "Fashion",
  Games = "Games",
  BooksAndMovies = "Books and Movies",
  SportsAndFitness = "Sports and Fitness",
}
